package ch.bfh.monopoly.tile;

public enum Step {
		JAIL_START,
		JAIL_CARD,
		JAIL_PAY,
		JAIL_ROLL,
		JAIL_ROLL_FAILURE,
		ROLL_NORMAL,
		ROLL_NORMAL2,
		SECOND_STEP,
		TILE_NOT_OWNED,
		TILE_NOT_OWNED2,
		TILE_OWNED,
		TILE_OWNED2,
		TILE_OWNED_BY_YOU,
		PAID_INCOME_TAX,
		LEAVE_FREEPARKING,
		DOUBLES_TRANSITION,
		DOUBLES_TO_JAIL,
		JAIL_FREED,
		GET_EVENT;
		
}

